Hr\EmployeeBundle\Entity\Employee:
    type: entity
    table: employee
    repositoryClass: Hr\EmployeeBundle\Entity\EmployeeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
        surname:
            type: string
            length: '45'
        itemStatus:
            type: smallint
            column: item_status
    lifecycleCallbacks: {  }
