parameters:
#    hr_employee.example.class: Hr\EmployeeBundle\Example

services:
#    hr_employee.example:
#        class: %hr_employee.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
