parameters:
#    hr_time_managment.example.class: Hr\TimeManagmentBundle\Example

services:
#    hr_time_managment.example:
#        class: %hr_time_managment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
